//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wanderlust.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMENT
    {
        public int cmnt_id { get; set; }
        public int blog_id { get; set; }
        public string content { get; set; }
        public int user_id { get; set; }
        public System.DateTime date_posted { get; set; }
    
        public virtual BLOG BLOG { get; set; }
        public virtual USER USER { get; set; }
    }
}
