//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wanderlust.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITINERARY_DESTINATION
    {
        public int id { get; set; }
        public int itinerary_id { get; set; }
        public int dest_id { get; set; }
    
        public virtual DESTINATION DESTINATION { get; set; }
        public virtual ITINERARY ITINERARY { get; set; }
    }
}
