//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wanderlust.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REVIEW
    {
        public int review_id { get; set; }
        public int dest_id { get; set; }
        public int rating { get; set; }
        public string content { get; set; }
        public int user_id { get; set; }
        public System.DateTime review_date { get; set; }
    
        public virtual DESTINATION DESTINATION { get; set; }
        public virtual USER USER { get; set; }
    }
}
