//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wanderlust.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLOG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BLOG()
        {
            this.COMMENTs = new HashSet<COMMENT>();
            this.BLOG_LIKE = new HashSet<BLOG_LIKE>();
        }
    
        public int blog_id { get; set; }
        public int author_id { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public System.DateTime publication_date { get; set; }
        public Nullable<int> like_count { get; set; }
    
        public virtual AUTHOR AUTHOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENT> COMMENTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BLOG_LIKE> BLOG_LIKE { get; set; }
    }
}
