//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wanderlust.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOKING()
        {
            this.PAYMENTs = new HashSet<PAYMENT>();
        }
    
        public int booking_id { get; set; }
        public System.DateTime bk_date { get; set; }
        public string status { get; set; }
        public int user_id { get; set; }
        public string bk_type { get; set; }
        public int trip_id { get; set; }
        public System.DateTime travel_start_date { get; set; }
        public System.DateTime travel_end_date { get; set; }
        public int numtravelers { get; set; }
        public decimal bk_cost { get; set; }
    
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAYMENT> PAYMENTs { get; set; }
    }
}
