//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wanderlust.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESTINATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DESTINATION()
        {
            this.ITINERARY_DESTINATION = new HashSet<ITINERARY_DESTINATION>();
            this.PACKAGE_DESTINATION = new HashSet<PACKAGE_DESTINATION>();
            this.REVIEWs = new HashSet<REVIEW>();
            this.WISHLISTs = new HashSet<WISHLIST>();
        }
    
        public int dest_id { get; set; }
        public string destName { get; set; }
        public string image { get; set; }
        public decimal price { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITINERARY_DESTINATION> ITINERARY_DESTINATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACKAGE_DESTINATION> PACKAGE_DESTINATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REVIEW> REVIEWs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WISHLIST> WISHLISTs { get; set; }
    }
}
