//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wanderlust.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT
    {
        public int payment_id { get; set; }
        public int booking_id { get; set; }
        public string payMethod { get; set; }
        public decimal amount { get; set; }
        public System.DateTime payment_date { get; set; }
    
        public virtual BOOKING BOOKING { get; set; }
    }
}
