//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wanderlust.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WanderlustEntities : DbContext
    {
        public WanderlustEntities()
            : base("name=WanderlustEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUTHOR> AUTHORs { get; set; }
        public virtual DbSet<BLOG> BLOGs { get; set; }
        public virtual DbSet<BOOKING> BOOKINGs { get; set; }
        public virtual DbSet<COMMENT> COMMENTs { get; set; }
        public virtual DbSet<DESTINATION> DESTINATIONs { get; set; }
        public virtual DbSet<ITINERARY> ITINERARies { get; set; }
        public virtual DbSet<ITINERARY_DESTINATION> ITINERARY_DESTINATION { get; set; }
        public virtual DbSet<PACKAGE> PACKAGEs { get; set; }
        public virtual DbSet<PACKAGE_DESTINATION> PACKAGE_DESTINATION { get; set; }
        public virtual DbSet<PAYMENT> PAYMENTs { get; set; }
        public virtual DbSet<REVIEW> REVIEWs { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
        public virtual DbSet<WISHLIST> WISHLISTs { get; set; }
        public virtual DbSet<BLOG_LIKE> BLOG_LIKE { get; set; }
    }
}
